services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: wanted_pre_onboarding_backend
      MYSQL_USER: newbie
      MYSQL_PASSWORD: newbie-password
  app:
    image: wanted-pre-onboarding-backend:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
