spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/wanted_pre_onboarding_backend?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: newbie
    password: newbie-password
    driver-class-name: com.mysql.cj.jdbc.Driver
